# Copyright (c) 2023-present The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/license/mit.

name: CI
on:
  # See: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request.
  pull_request:
  # See: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push.
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  CI_FAILFAST_TEST_LEAVE_DANGLING: 1  # GHA does not care about dangling processes and setting this variable avoids killing the CI script itself on error
  CIRRUS_CACHE_HOST: http://127.0.0.1:12321/ # When using Cirrus Runners this host can be used by the docker `gha` build cache type.
  REPO_USE_CIRRUS_RUNNERS: 'bitcoin/bitcoin' # Use cirrus runners and cache for this repo, instead of falling back to the slow GHA runners

defaults:
  run:
    # Enforce fail-fast behavior for all platforms.
    # See: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  runners:
    name: '[meta] determine runners'
    runs-on: ubuntu-slim
    outputs:
      provider: ${{ steps.runners.outputs.provider }}
    steps:
      - &ANNOTATION_PR_NUMBER
        name: Annotate with pull request number
        # This annotation is machine-readable and can be used to assign a check
        # run to its corresponding pull request. Running in all check runs is
        # required, because check re-runs discard the annotations of other
        # tasks in the test suite.
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "::notice title=debug_pull_request_number_str::${{ github.event.number }}"
          fi
      - id: runners
        run: |
          if [[ "${REPO_USE_CIRRUS_RUNNERS}" == "${{ github.repository }}" ]]; then
            echo "provider=cirrus" >> "$GITHUB_OUTPUT"
            echo "::notice title=Runner Selection::Using Cirrus Runners"
          else
            echo "provider=gha" >> "$GITHUB_OUTPUT"
            echo "::notice title=Runner Selection::Using GitHub-hosted runners"
          fi

  windows-native-dll:
    name: ${{ matrix.job-name }}
    runs-on: windows-2025-vs2026

    if: ${{ vars.SKIP_BRANCH_PUSH != 'true' || github.event_name == 'pull_request' }}

    env:
      PYTHONUTF8: 1
      TEST_RUNNER_TIMEOUT_FACTOR: 40

    strategy:
      fail-fast: false
      matrix:
        job-type: [standard, fuzz]
        include:
          - job-type: standard
            job-name: 'Windows native, VS'
          - job-type: fuzz
            job-name: 'Windows native, fuzz, VS'

    steps:
      - *ANNOTATION_PR_NUMBER

      - &CHECKOUT
        name: Checkout
        uses: actions/checkout@v6
        with:
          # Ensure the latest merged pull request state is used, even on re-runs.
          ref: &CHECKOUT_REF_TMPL ${{ github.event_name == 'pull_request' && github.ref || '' }}

      - &IMPORT_VS_ENV
        name: Import Visual Studio env vars
        run: py -3 .github/ci-windows.py "standard" github_import_vs_env

      - name: Get tool information
        run: |
          set -o errexit -o pipefail -o xtrace -o nounset

          cmake -version | tee cmake_version
          echo '---'
          msbuild.exe -version | tee msbuild_version
          echo "${VCToolsVersion-}" | tee toolset_version
          py -3 --version
          bash --version

      - shell: pwsh
        run: |
          vcpkg x-update-baseline
          git diff

      - name: Restore vcpkg downloads cache
        id: vcpkg-downloads-cache
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/AppData/Local/vcpkg/downloads/*
            !~/AppData/Local/vcpkg/downloads/tools
          key: ${{ github.job }}-vcpkg-downloads-${{ hashFiles('vcpkg.json') }}

      - name: Restore vcpkg binary cache
        uses: actions/cache/restore@v5
        id: vcpkg-binary-cache
        with:
          path: ~/AppData/Local/vcpkg/archives
          key: ${{ github.job }}-vcpkg-binary-release-${{ hashFiles('cmake_version', 'msbuild_version', 'toolset_version', 'vcpkg.json') }}

      - name: Generate build system
        run: |
          py -3 .github/ci-windows.py ${{ matrix.job-type }} generate

      - name: Save vcpkg binary cache
        uses: actions/cache/save@v5
        if: github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch && steps.vcpkg-binary-cache.outputs.cache-hit != 'true' && matrix.job-type == 'standard'
        with:
          path: ~/AppData/Local/vcpkg/archives
          key: ${{ steps.vcpkg-binary-cache.outputs.cache-primary-key }}

      - name: Save vcpkg downloads cache
        uses: actions/cache/save@v5
        # Only save cache from the 'standard' job, as it includes the necessary downloads for other jobs in the matrix. If the matrix is modified, this may need amending.
        if: github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch && steps.vcpkg-binary-cache.outputs.cache-hit != 'true' && steps.vcpkg-downloads-cache.outputs.cache-hit != 'true' && matrix.job-type == 'standard'
        with:
          path: |
            ~/AppData/Local/vcpkg/downloads/*
            !~/AppData/Local/vcpkg/downloads/tools  # Cache the tools once as archives, but not redundantly in extracted form.
          key: ${{ steps.vcpkg-downloads-cache.outputs.cache-primary-key }}

      - name: Build
        run: |
          py -3 .github/ci-windows.py ${{ matrix.job-type }} build

      - name: Check executable manifests
        run: |
          py -3 .github/ci-windows.py ${{ matrix.job-type }} check_manifests

      - name: Prepare tests
        run: |
          py -3 .github/ci-windows.py ${{ matrix.job-type }} prepare_tests

      - name: Run tests
        env:
          TEST_RUNNER_EXTRA: "--timeout-factor=${{ env.TEST_RUNNER_TIMEOUT_FACTOR }} ${{ case(github.event_name == 'pull_request', '', '--extended') }}"
        run: |
          py -3 .github/ci-windows.py ${{ matrix.job-type }} run_tests

  record-frozen-commit:
    # Record frozen commit, so that the native tests on cross-builds can run on
    # the exact same commit id of the build.
    name: '[meta] record frozen commit'
    runs-on: ubuntu-slim
    outputs:
      commit: ${{ steps.record-commit.outputs.commit }}
    steps:
      - *ANNOTATION_PR_NUMBER
      - *CHECKOUT
      - name: Record commit
        id: record-commit
        run: echo "commit=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
